adam_beta1: 0.9
adam_beta2: 0.9999
adam_eps: 1e-08
amp: true
backend: null
batch_size: 16
behavior_mode: 0
center_crop: 1.0
clear_output_dir: true
core: vit
core_lr: 0.001647
core_reg_scale: 0.5379
criterion: poisson
cropper_reg_scale: 0.0
dataset: ../V1T/data/sensorium
deterministic: false
device: cuda
disable_bias: false
dpi: 120
drop_path: 0.0
dropout: 0.2544
ds_name: sensorium
ds_scale: 1
emb_dim: 156
epochs: 400
format: svg
git_hash: 1637c35
grad_checkpointing: true
gray_scale: false
hostname: phobos
input_shape: [1, 144, 256]
limit_data: null
lr: 0.001647
micro_batch_size: 16
mlp_dim: 488
mouse_ids: [S0]
num_blocks: 4
num_heads: 4
num_workers: 2
output_dir: runs_debug/att_readout/new_M1_s_1_emb_160_init
output_shapes:
  S0: [7776]
p_dropout: 0.0229
patch_mode: 0
patch_size: 8
patch_stride: 1
pretrain_core: ''
readout: attention
readout_reg_scale: 0.0076
resize_image: 1
save_plots: false
seed: 1
shift_mode: 2
shifter_reg_scale: 0.0
t_dropout: 0.2544
trainable_params: 4014078
use_lsa: false
use_wandb: true
verbose: 1
wandb_group: redo-attention-readout
wandb_project: sensorium
