adam_beta1: 0.9
adam_beta2: 0.9999
adam_eps: 1e-08
amp: true
backend: null
batch_size: 16
behavior_mode: 0
center_crop: 1.0
clear_output_dir: false
core: multimodalattention
core_lr: 0.001647
core_reg_scale: 0.5379
criterion: poisson
cropper_reg_scale: 0.0
dataset: data/sensorium
deterministic: false
device: cpu
disable_bias: false
dpi: 120
drop_path: 0.0
ds_name: sensorium
ds_scale: 1
emb_dim: 155
emb_dim_readout: 160
emb_dim_tokenizer: 150
epochs: 400
format: svg
frac_input_neurons: 0.25
git_hash: 7b86e52
grad_checkpointing: false
gray_scale: false
hostname: phobos
input_shape: [1, 144, 256]
key_embedding: 1
limit_data: null
lr: 0.001647
micro_batch_size: 16
micro_batch_step_size: 8
mlp_dim: 488
mouse_ids: [1_s3_45]
num_blocks: 4
num_heads: 4
num_modes: 2
num_samples_per_token: 1
num_workers: 2
output_dir: runs_modular/input_attention/debug_input_neurons_at
output_shapes:
  1_s3_45: [8736]
p_dropout: 0.0229
patch_mode: 0
patch_size: 8
patch_stride: 1
pretrain_core: ''
r_dropout: 0.2544
readout: attention
readout_reg_scale: 0.0076
resize_image: 1
samples_per_token: 1
save_plots: false
seed: 1
shift_mode: 2
shifter_reg_scale: 0.0
start_micro_batch_size: 1
t_dropout: 0.2544
tokenize_neurons: 1
trainable_params: 4463861
use_lsa: false
use_wandb: false
value_embedding: 1
verbose: 1
wandb_group: ''
wandb_project: sensorium
